apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: monitoring
  name: prometheus-coredns-base-alerts
spec:
  groups:
  - name: ./coredns-base-alert.rules
    rules:
      - alert: CorednsPanicCount
        expr: increase(coredns_panic_count_total[1m]) > 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: CoreDNS Panic Count (instance {{ $labels.instance }})
          description: "Number of CoreDNS panics encountered\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"